spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1
